### ISSUE TITLE
loss is NaN for speech example

### ISSUE THREAD

**Issue by xinq2016** [deepgram/kur#21]
Is there any one get the same issue? train/valid loss became NaN after few iters

**Comment by liaoweiguo** [comment]
penalty too much? try again, maybe

**Comment by xinq2016** [comment]
What penalty do you exactly mean?
The optimizer of GRU net is assigned as following:

optimizer:
    name: sgd
    nesterov: yes
    learning_rate: 2e-4
    momentum: 0.9
    clip:
      norm: 100

**Comment by ajsyp** [comment]
Things to try:
- Lower the learning rate.
- Use TensorFlow as the backend (Theano seems to NaN more readily than TF)
- Try training on utterances that are shorter (1-5 seconds) in batches close to the same length. One easy way to do this is to set a maximum audio duration like this:
```
train:
  data:
    - speech_recognition:
        max_duration: 5
        # other parameters ...
```
