### ISSUE TITLE
a tiny error in character_rnn example kurfile

### ISSUE THREAD

**Issue by EmbraceLife** [deepgram/kur#29]
Hi @noajshu ,
Thanks for your character example, it is great! 

@ajsyp has pointed to me something is not exactly right with the weights, and now I realized the tiny issue there.  Inside kurfile.yaml, is the following `weights` what you wanted, instead of [here](https://github.com/deepgram/kur/blob/master/examples/language-model/model/kurfile.yaml#L46): 

```yml
train:
  data:
    - jsonl: ../data/train.jsonl
  epochs: 5
  weights:
    initial: best.w.kur
    best: best.w.kur
    last: last.w.kur
  log: log


validate:
  data:
    - jsonl: ../data/validate.jsonl
  weights: best.w.kur


test:
  data:
    - jsonl: ../data/test.jsonl
  weights: best.w.kur
```
