### ISSUE TITLE
dependency graph resolution

### ISSUE THREAD

**Issue by josh-gree** [deepgram/kur#39]
Hi 

So I have run into the following value error;

ValueError: No change during dependency graph resolution. There is something wrong with the graph.

It occurs when trying to use kurfile.get_model() on the following .yml

```
settings:
  layer_reps: 2
  module_reps: 3
  cs: 16


model:

 - input:
    shape: [512,512,1]
   name: in

 - for:
    range: "{{module_reps}}"
    with_index: j
    iterate:

     - for:
        range: "{{layer_reps}}"
        with_index: i
        iterate:

         - convolution:
            kernels: "{{cs*2**j}}"
            size: [3,3]
           name: "m{{j}}_c{{i}}"
           sink: yes

         - activation: relu

     - pool:
        size: [2,2]
        strides: [2,2]
        type: max
       name: "m{{j}}_p"
       sink: yes

     - dense:
        size: "{{cs*2**module_reps}}"
       sink: yes
       name: middle
```

Now the issue seems to be in the naming of the dense layer. Without the name everything works fine...

Thanks Josh
