### ISSUE TITLE
plot_weights hook: plot unlimited weights; access weights directly from Executor.model not external files

### ISSUE THREAD

**Issue by EmbraceLife** [deepgram/kur#68]
Now, I have managed to plot the convolutional weights by the following kurfile: 
```yaml
hooks:
    - plot_weights:
        weight_file: cifar.best.valid.w
        weight_keywords1: ["convolution.0", "kernel"]
        weight_keywords2: ["convolution.1", "kernel"]
```
In my `plot_weights_hook.py`, I get `weight_keywords1`, `weight_keywords2` into hooks through `__init__()`: 

```python
def __init__(self, weight_file, weight_keywords1, weight_keywords2, *args, **kwargs):
		""" Creates a new plotting hook, get plot filenames and matplotlib ready.
		"""
```
**my question**:

if I want to plot more convolutional weights, say `weight_keywords3`, `weight_keywords4`, `weight_keywords5`, do I have to change the source code, by adding them into `__init__` like above? 

Can `**kwargs` somehow help me avoid changing source every time I want to plot more weights? If so, how? 

Thanks!

**Comment by ajsyp** [comment]
You can do it two ways. First, yes, you could use **kwargs to do it, but then you need to be careful to make sure that you pass through the correct pieces of kwargs to the base class constructor (there are lots of ways you can envision this, but all are harder to maintain or are fragile). A better way to do it would be to simply add another layer of indirection:
```
hooks:
  - plot_weights
      weight_file: cifar.best.valid.w
      with_weights:
        - ['convolution.0', 'kernel']
        - ['convolution.1', 'kernel']
        - ['convolution.2', 'kernel']
        - ...
```
And then your constructor signature looks like this:
def __init__(self, weight_file, with_weights, *args, **kwargs)
